language: python

python:
  - "3.6"

services: sqlite3

env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite.settings"
    - PYTHONPATH="/home/travis/build/Blazusiak/CMPUT404LAB6"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true

#commands to install dependencies
install:
  - pip install -q -r requirements.txt

before_script:
  - python manage.py migrate 

#command to run the test suite
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
